CREATE TABLE AJOUMEMBER(
ID VARCHAR2(30) PRIMARY KEY,
NAME VARCHAR2(30) NOT NULL,
CLASSIFICATION NUMBER NOT NULL
)
// 0은 학생 1은 교수

CREATE TABLE MEMBERSHIP(
ID VARCHAR2(30) PRIMARY KEY,
PASSWORD VARCHAR2(20) NOT NULL,
EMAIL VARCHAR2(45) NOT NULL,		
CONSTRAINT ID_FK FOREIGN KEY(ID) REFERENCES AJOUMEMBER(ID)
)

INSERT INTO AJOUMEMBER VALUES ('1','SON','0');
INSERT INTO AJOUMEMBER VALUES ('2','KIM','0');
INSERT INTO AJOUMEMBER VALUES ('3','LEE','0');
INSERT INTO AJOUMEMBER VALUES ('4','LEESW','1');

SELECT * FROM AJOUMEMBER;

INSERT INTO MEMBERSHIP VALUES('1','201420929','AJS@AJOU.COM');
INSERT INTO MEMBERSHIP VALUES('2','1234','ASS@AJOU.COM');
INSERT INTO MEMBERSHIP VALUES('3','1234','ABS@AJOU.COM');
INSERT INTO MEMBERSHIP VALUES('4','1234','AAS@AJOU.COM');


SELECT A.NAME, A.CLASSIFICATION,M.EMAIL
FROM AJOUMEMBER A, MEMBERSHIP M
WHERE A.ID= M.ID AND A.CLASSIFICATION=1;

SELECT A.NAME, A.CLASSIFICATION, M.PASSWORD, M.ID
FROM MEMBERSHIP M, AJOUMEMBER A
WHERE A.ID = M. ID;


SELECT A.NAME, A.CLASSIFICATION, M.PASSWORD, M.ID   
FROM   MEMBERSHIP M, AJOUMEMBER A 
WHERE A.ID=M.ID AND M.ID='4' AND M.PASSWORD='1234';
 


select id,password,email from MEMBERSHIP  where id='2' and password='1234'