CREATE TABLE AJOUMEMBER(
ID VARCHAR2(30) PRIMARY KEY,
NAME VARCHAR2(30) NOT NULL,
CLASSIFICATION NUMBER NOT NULL
)
// 0은 학생 1은 교수

CREATE TABLE MEMBERSHIP(
ID VARCHAR2(30) PRIMARY KEY,
PASSWORD VARCHAR2(20) NOT NULL,
EMAIL VARCHAR2(45) NOT NULL,		
CONSTRAINT ID_FK FOREIGN KEY(ID) REFERENCES AJOUMEMBER(ID)
)


CREATE TABLE COURSES(
COURSEID VARCHAR2(30) PRIMARY KEY,
COURSENAME VARCHAR2(50) NOT NULL,
SEMESTER VARCHAR2(10) NOT NULL,
COURSE_TIME VARCHAR2(30) NOT NULL
)
DROP TABLE TAKE_COURSE

INSERT INTO COURSES VALUES ('ABV','syspro','2','a');
INSERT INTO COURSES VALUES ('DXI','SWE','2','a');
INSERT INTO COURSES VALUES ('S9E','JAVA','2','a');

INSERT INTO TAKE_COURSE VALUES ('ABV','4');
INSERT INTO TAKE_COURSE VALUES ('DXI','4');
INSERT INTO TAKE_COURSE VALUES ('S9E','4');



SELECT C.COURSENAME
FROM AJOUMEMBER A, TAKE_COURSE T, COURSES C
WHERE A.ID='4' AND C.COURSEID=T.COURSEID;

CREATE TABLE TAKE_COURSE(
COURSEID VARCHAR2(30) NOT NULL,
ID VARCHAR2(30) NOT NULL,
CONSTRAINT FK_COURSEID FOREIGN KEY(COURSEID) REFERENCES COURSES(COURSEID),
CONSTRAINT FK_TAKECOURSE_ID FOREIGN KEY(ID) REFERENCES AJOUMEMBER(ID),
CONSTRAINT PK_TAKECOURSE PRIMARY KEY(COURSEID,ID)
)

		
create table SEND_QUESTION
(
No INT NOT NULL,
CourseID VARCHAR(11) NOT NULL,
ID CHAR(9) NOT NULL,
Content VARCHAR(1000) NOT NULL,
Mode CHAR(1) NOT NULL,
PRIMARY KEY(No),
FOREIGN KEY(CourseID) REFERENCES COURSES(CourseID)
		ON DELETE CASCADE	ON UPDATE CASCADE,
FOREIGN KEY(ID) REFERENCES MEMBERSHIP(ID)
		ON DELETE CASCADE	ON UPDATE CASCADE);



SELECT C.COURSENAME
		FROM
		AJOUMEMBER A, TAKE_COURSE T, COURSES C
		WHERE A.ID=T.ID AND A.ID='4' AND
		C.COURSEID=T.COURSEID


INSERT INTO AJOUMEMBER VALUES ('professor','LEESW','1');
INSERT INTO AJOUMEMBER VALUES ('student','sjm','0');


INSERT INTO AJOUMEMBER VALUES ('1','SON','0');
INSERT INTO AJOUMEMBER VALUES ('2','KIM','0');
INSERT INTO AJOUMEMBER VALUES ('3','LEE','0');
INSERT INTO AJOUMEMBER VALUES ('4','LEESW','1');
INSERT INTO AJOUMEMBER VALUES ('hwang','hwang','1');
SELECT * FROM AJOUMEMBER;

INSERT INTO MEMBERSHIP VALUES('hwang','1234','AJS@AJOU.COM');
INSERT INTO MEMBERSHIP VALUES('professor','1234','ASS@AJOU.COM');
INSERT INTO MEMBERSHIP VALUES('student','1234','ABS@AJOU.COM');
INSERT INTO MEMBERSHIP VALUES('4','1234','AAS@AJOU.COM');


SELECT A.NAME, A.CLASSIFICATION,M.EMAIL
FROM AJOUMEMBER A, MEMBERSHIP M
WHERE A.ID= M.ID AND A.CLASSIFICATION=1;

SELECT A.NAME, A.CLASSIFICATION, M.PASSWORD, M.ID
FROM MEMBERSHIP M, AJOUMEMBER A
WHERE A.ID = M. ID;


SELECT A.NAME, A.CLASSIFICATION, M.PASSWORD, M.ID   
FROM   MEMBERSHIP M, AJOUMEMBER A 
WHERE A.ID=M.ID AND M.ID='4' AND M.PASSWORD='1234';
 



select id,password,email from MEMBERSHIP  where id='2' and password='1234'